# Generated by Django 5.2.14 on 2026-05-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
